androidApp/build.gradle.kts, shared/build.gradle.kts, shared/src/commonMain/kotlin/utils/HTTPManager.kt, shared/src/commonMain/kotlin/views/SettingsView.kt
=> HTTPManager simple HTTP Get working

shared/src/commonMain/kotlin/utils/HTTPManager.kt, shared/src/commonMain/kotlin/views/SettingsView.kt
Tested on iOS and Android
just test version. method has to be reworked
=> HTTPManager post request with jsonBody

shared/src/commonMain/kotlin/App.kt, shared/src/commonMain/kotlin/account/User.kt, shared/src/commonMain/kotlin/account/UserInterface.kt, shared/src/commonMain/kotlin/account/manager/CreationManager.kt, shared/src/commonMain/kotlin/account/utilities/RoleType.kt, shared/src/commonMain/kotlin/account/utilities/UUID.kt, shared/src/commonMain/kotlin/managers/HTTPManager.kt, shared/src/commonMain/kotlin/managers/exceptions/ExceptionHandler.kt, shared/src/commonMain/kotlin/managers/exceptions/NException.kt, shared/src/commonMain/kotlin/utilities/DateUtil.kt, shared/src/commonMain/kotlin/utilities/EncryptionUtil.kt, shared/src/commonMain/kotlin/utilities/MonthCalc.kt, shared/src/commonMain/kotlin/views/HomeScreen.kt, shared/src/commonMain/kotlin/views/SettingsView.kt
User + Userinterface start
ExceptionHandler
=> Restructure

shared/src/commonMain/kotlin/account/User.kt, shared/src/commonMain/kotlin/account/UserInterface.kt, shared/src/commonMain/kotlin/managers/HTTPManager.kt
=> UserInterface update

shared/src/commonMain/kotlin/account/manager/AuthCodeManager.kt, shared/src/commonMain/kotlin/account/manager/CreationManager.kt, shared/src/commonMain/kotlin/managers/HTTPManager.kt, shared/src/commonMain/kotlin/managers/exceptions/ExceptionHandler.kt, shared/src/commonMain/kotlin/managers/exceptions/NException.kt
commenting
email check availability
=> Performance updates

shared/src/commonMain/kotlin/account/User.kt, shared/src/commonMain/kotlin/account/UserInterface.kt, shared/src/commonMain/kotlin/managers/HTTPManager.kt, shared/src/commonMain/kotlin/views/SettingsView.kt
=> User getEmail method

shared/src/commonMain/kotlin/App.kt, shared/src/commonMain/kotlin/utilities/presentation/BottomSheet.kt, shared/src/commonMain/kotlin/views/DetailScreen.kt, shared/src/commonMain/kotlin/views/HomeScreen.kt, shared/src/commonMain/kotlin/views/SettingsView.kt, shared/src/commonMain/kotlin/views/TestView.kt
=> bottomsheets

shared/src/commonMain/kotlin/App.kt, shared/src/commonMain/kotlin/event/TrendWaveEvent.kt, shared/src/commonMain/kotlin/event/TrendWaveViewModel.kt, shared/src/commonMain/kotlin/views/LoginScreen.kt, shared/src/commonMain/kotlin/views/RegisterScreen.kt
Navigate between Login and Register screen #55
Added working Error line #54
Tested-by: @FelixHennerich
Tested-on: IOS + Android
=> Navigate between Login and Register screen

androidApp/src/androidMain/kotlin/com/myapplication/MainActivity.kt, shared/src/androidMain/kotlin/account/image/ImageStorage.kt, shared/src/androidMain/kotlin/di/AppModule.kt, shared/src/androidMain/kotlin/main.android.kt, shared/src/commonMain/kotlin/App.kt, shared/src/commonMain/kotlin/account/image/ImageDataSource.kt, shared/src/commonMain/kotlin/account/image/ImageStorage.kt, shared/src/commonMain/kotlin/account/image/Photo.kt, shared/src/commonMain/kotlin/account/image/StorageImageDataSource.kt, shared/src/commonMain/kotlin/di/AppModule.kt, shared/src/commonMain/kotlin/event/TrendWaveViewModel.kt, shared/src/commonMain/kotlin/views/SettingsScreen.kt, shared/src/iosMain/kotlin/account.image/ImageStorage.kt, shared/src/iosMain/kotlin/di/AppModule.kt, shared/src/iosMain/kotlin/main.ios.kt
ImageAPI working but still in work
Tested-by: @FelixHennerich
Tested-on: Android
=> AppModule for ImageDataSource

shared/src/commonMain/kotlin/App.kt, shared/src/commonMain/kotlin/account/image/StorageImageDataSource.kt, shared/src/commonMain/kotlin/views/LoginScreen.kt, shared/src/commonMain/kotlin/views/RegisterScreen.kt
=> Added Logo

shared/src/commonMain/kotlin/App.kt, shared/src/commonMain/kotlin/account/manager/CreationManager.kt, shared/src/commonMain/kotlin/event/TrendWaveEvent.kt, shared/src/commonMain/kotlin/event/TrendWaveViewModel.kt, shared/src/commonMain/kotlin/managers/exceptions/ExceptionHandler.kt, shared/src/commonMain/kotlin/managers/exceptions/NException.kt, shared/src/commonMain/kotlin/views/RegisterScreen.kt
- Error line working
- redirect working
- aligned checkbox on android #71
=> Account creation working in app

shared/src/commonMain/kotlin/views/LoginScreen.kt
=> LoginManager continued

shared/src/commonMain/kotlin/App.kt, shared/src/commonMain/kotlin/account/User.kt, shared/src/commonMain/kotlin/account/UserInterface.kt, shared/src/commonMain/kotlin/account/manager/LoginManager.kt, shared/src/commonMain/kotlin/event/TrendWaveEvent.kt, shared/src/commonMain/kotlin/event/TrendWaveViewModel.kt, shared/src/commonMain/kotlin/managers/HTTPManager.kt, shared/src/commonMain/kotlin/managers/exceptions/ExceptionHandler.kt, shared/src/commonMain/kotlin/managers/exceptions/NException.kt, shared/src/commonMain/kotlin/views/LoginScreen.kt, shared/src/commonMain/kotlin/views/SettingsScreen.kt
=> LoginManager finished

shared/src/androidMain/kotlin/di/AppModule.kt, shared/src/androidMain/kotlin/managers/DataStorageManager.kt, shared/src/commonMain/kotlin/App.kt, shared/src/commonMain/kotlin/di/AppModule.kt, shared/src/commonMain/kotlin/managers/DataStorageManager.kt, shared/src/commonMain/kotlin/views/HomeScreen.kt, shared/src/commonMain/kotlin/views/LoginScreen.kt, shared/src/commonMain/kotlin/views/SettingsScreen.kt, shared/src/iosMain/kotlin/di/AppModule.kt, shared/src/iosMain/kotlin/managers/DataStorageManager.kt
=> LocalDataStorage

shared/src/commonMain/kotlin/event/TrendWaveEvent.kt, shared/src/commonMain/kotlin/event/TrendWaveState.kt, shared/src/commonMain/kotlin/event/TrendWaveViewModel.kt, shared/src/commonMain/kotlin/post/Post.kt, shared/src/commonMain/kotlin/post/PostLoader.kt, shared/src/commonMain/kotlin/post/presentation/AddPostSheet.kt, shared/src/commonMain/kotlin/post/presentation/PostDisplay.kt, shared/src/commonMain/kotlin/views/HomeScreen.kt
Random 5 posts will be displayed on home screen
=> Postuploader and postloader working with database

shared/src/commonMain/kotlin/App.kt, shared/src/commonMain/kotlin/account/User.kt, shared/src/commonMain/kotlin/account/UserInterface.kt, shared/src/commonMain/kotlin/account/manager/LoginManager.kt, shared/src/commonMain/kotlin/account/presentation/ProfileSheet.kt, shared/src/commonMain/kotlin/event/TrendWaveEvent.kt, shared/src/commonMain/kotlin/event/TrendWaveState.kt, shared/src/commonMain/kotlin/event/TrendWaveViewModel.kt, shared/src/commonMain/kotlin/post/PostLoader.kt, shared/src/commonMain/kotlin/post/presentation/AddPostSheet.kt, shared/src/commonMain/kotlin/post/presentation/PostDisplay.kt, shared/src/commonMain/kotlin/views/HomeScreen.kt, shared/src/commonMain/kotlin/views/LoadingScreen.kt, shared/src/commonMain/kotlin/views/LoginScreen.kt, shared/src/commonMain/kotlin/views/RegisterScreen.kt
- Delete as own user or Admin
Post add bug fixed (Empty Post)
LoadingScreen + Keep Loggedin #85
Userclass #getRole Method
ProfileSheet started not fully working
=> Post deletion database + local

shared/src/commonMain/kotlin/App.kt, shared/src/commonMain/kotlin/account/User.kt, shared/src/commonMain/kotlin/account/UserInterface.kt, shared/src/commonMain/kotlin/account/manager/LoginManager.kt, shared/src/commonMain/kotlin/account/presentation/ProfileSheet.kt, shared/src/commonMain/kotlin/event/TrendWaveEvent.kt, shared/src/commonMain/kotlin/event/TrendWaveState.kt, shared/src/commonMain/kotlin/event/TrendWaveViewModel.kt, shared/src/commonMain/kotlin/managers/HTTPManager.kt, shared/src/commonMain/kotlin/post/presentation/AddPostSheet.kt, shared/src/commonMain/kotlin/utilities/presentation/BottomSheet.kt, shared/src/commonMain/kotlin/views/HomeScreen.kt
=> ProfileSheet looking good and working

androidApp/src/androidMain/AndroidManifest.xml, shared/src/commonMain/kotlin/App.kt, shared/src/commonMain/kotlin/account/AppUser.kt, shared/src/commonMain/kotlin/account/RESTfulUserManager.kt, shared/src/commonMain/kotlin/account/UserInterface.kt, shared/src/commonMain/kotlin/account/manager/FollowManager.kt, shared/src/commonMain/kotlin/account/manager/LoginManager.kt, shared/src/commonMain/kotlin/account/presentation/ProfileSheet.kt, shared/src/commonMain/kotlin/event/TrendWaveEvent.kt, shared/src/commonMain/kotlin/event/TrendWaveState.kt, shared/src/commonMain/kotlin/event/TrendWaveViewModel.kt, shared/src/commonMain/kotlin/managers/exceptions/ExceptionHandler.kt, shared/src/commonMain/kotlin/managers/exceptions/NException.kt, shared/src/commonMain/kotlin/post/RESTfulPostManager.kt, shared/src/commonMain/kotlin/post/presentation/AddPostSheet.kt, shared/src/commonMain/kotlin/post/presentation/PostDisplay.kt, shared/src/commonMain/kotlin/views/HomeScreen.kt, shared/src/commonMain/kotlin/views/LoadingScreen.kt, shared/src/commonMain/kotlin/views/LoginScreen.kt, shared/src/commonMain/kotlin/views/RegisterScreen.kt
New server (not completely integrated)
=> FollowManager started not finished

shared/src/commonMain/kotlin/App.kt, shared/src/commonMain/kotlin/views/LoginScreen.kt, shared/src/commonMain/kotlin/views/sheet/SettingsSheet.kt
Soweit is das ui fertig nur funktionen fehlen noch
=> updated SettingsSheet

iosApp/iosApp/Info.plist, shared/src/androidMain/kotlin/managers/DataStorageManager.kt, shared/src/commonMain/kotlin/App.kt, shared/src/commonMain/kotlin/account/manager/LoginManager.kt, shared/src/iosMain/kotlin/managers/DataStorageManager.kt
=> #108 fixed

shared/src/commonMain/kotlin/App.kt, shared/src/commonMain/kotlin/account/AppUser.kt, shared/src/commonMain/kotlin/account/RESTfulUserManager.kt, shared/src/commonMain/kotlin/account/manager/FollowManagerClass.kt, shared/src/commonMain/kotlin/event/TrendWaveEvent.kt, shared/src/commonMain/kotlin/event/TrendWaveViewModel.kt, shared/src/commonMain/kotlin/post/RESTfulPostManager.kt, shared/src/commonMain/kotlin/views/LoadingScreen.kt, shared/src/commonMain/kotlin/views/LoginScreen.kt
Loginscreen enter on keyboardfixed
=> Followmanager working wothout error

shared/src/commonMain/kotlin/App.kt, shared/src/commonMain/kotlin/views/LoginScreen.kt, shared/src/commonMain/kotlin/views/RegisterScreen.kt
=> LoginScreen Registerscreen edited fixed text in the center

shared/src/commonMain/kotlin/App.kt, shared/src/commonMain/kotlin/event/TrendWaveEvent.kt, shared/src/commonMain/kotlin/event/TrendWaveState.kt, shared/src/commonMain/kotlin/event/TrendWaveViewModel.kt, shared/src/commonMain/kotlin/views/LoginScreen.kt, shared/src/commonMain/kotlin/views/sheet/ForgotPasswordSheet.kt
=> ForgotPasswordSheet.kt

shared/src/commonMain/kotlin/App.kt, shared/src/commonMain/kotlin/views/HomeScreen.kt, shared/src/commonMain/kotlin/views/sheet/SettingsSheet.kt
=> Logout working

shared/src/commonMain/kotlin/account/manager/CreationManager.kt, shared/src/commonMain/kotlin/views/RegisterScreen.kt
=> checks #160

shared/src/commonMain/kotlin/account/RESTfulUserManager.kt
=> Fixed #172

shared/src/commonMain/kotlin/account/presentation/ProfileSheet.kt, shared/src/commonMain/kotlin/post/presentation/AddPostSheet.kt, shared/src/commonMain/kotlin/post/presentation/PostDisplay.kt, shared/src/commonMain/kotlin/views/HomeScreen.kt, shared/src/commonMain/kotlin/views/presentation/PostButtons.kt
Home finished
Profile finished
post started
=> Color Manager working with blue colors

shared/src/commonMain/kotlin/App.kt, shared/src/commonMain/kotlin/event/TrendWaveState.kt, shared/src/commonMain/kotlin/event/events/ApplicationStartEvent.kt, shared/src/commonMain/kotlin/views/HomeScreen.kt
ApplicationStartEvent -> Load post data function
removed new load after 10 mins in HomeScreen
=> #183 fixed

shared/src/commonMain/kotlin/event/events/ApplicationStartEvent.kt, shared/src/commonMain/kotlin/event/events/FollowEvent.kt
=> blur fixed

shared/src/commonMain/kotlin/account/presentation/ProfileSheet.kt, shared/src/commonMain/kotlin/post/presentation/AddPostSheet.kt, shared/src/commonMain/kotlin/views/HomeScreen.kt
=> fixed #166

shared/src/commonMain/kotlin/account/presentation/ProfileSheet.kt
=> working ios updated https
